# Intro

Software for reading the .dat files, raw data from 4STAR

# imports and function

In [1]:
import numpy as np
import os

In [2]:
fp = 'C:\Users\Sunsat\Documents\Data\\20160208'

In [5]:
f = fp+'\\20160208_004_NIR_SUN.dat'

In [6]:
f

'C:\\Users\\Sunsat\\Documents\\Data\\20160208\\20160208_004_NIR_SUN.dat'

In [8]:
os.path.isfile(f)

True

In [15]:
d = np.genfromtxt(f,names=True,skip_header=9)

In [39]:
head = []
with open(f,'r') as ff:
    for line in ff:
        if line[0].isdigit():
           break
        else:
            head.append(line)

In [41]:
def get_header(f):
    head = []
    with open(f,'r') as ff:
        for line in ff:
            if line[0].isdigit():
               break
            else:
                head.append(line)
    numhead = len(head)-1
    return head,numhead

In [42]:
g = fp+'\\20160208_009_NIR_FORJ.dat'

In [43]:
h,n = get_header(g)

In [44]:
h

['%Mission: roof\n',
 '%Operator: SL\n',
 '%Detector Type: NIR\n',
 '%Detector SN: 0\n',
 '%Collection Code: 20130108\n',
 '%File Format Version: 20130108.000000\n',
 '%Observer Note: FORJ outside right after rotation \n',
 '%Offsets:  Azimuth=-4063 ,Elevation=-18140,AzPark=9000,ElPark=11550,SkyBarrellOffset=-417\n',
 '%20160208_009_NIR_FORJ.dat\n',
 'YYYY MM DD HH mm ss msec Str Md Zn       Lat       Lon       Alt  Headng   pitch    roll       Tst      Pst        RH AZstep Elstep    AZ_deg    El_deg   QdVlr   QdVtb  QdVtot AZcorr ELcorr   Tbox  Tprecon  RHprecon   Vdettemp   Tint AVG  Pix0 Pix1 Pix2 Pix3 Pix4 Pix5 Pix6 Pix7 Pix8 Pix9 Pix10 Pix11 Pix12 Pix13 Pix14 Pix15 Pix16 Pix17 Pix18 Pix19 Pix20 Pix21 Pix22 Pix23 Pix24 Pix25 Pix26 Pix27 Pix28 Pix29 Pix30 Pix31 Pix32 Pix33 Pix34 Pix35 Pix36 Pix37 Pix38 Pix39 Pix40 Pix41 Pix42 Pix43 Pix44 Pix45 Pix46 Pix47 Pix48 Pix49 Pix50 Pix51 Pix52 Pix53 Pix54 Pix55 Pix56 Pix57 Pix58 Pix59 Pix60 Pix61 Pix62 Pix63 Pix64 Pix65 Pix66 Pix67 Pix68 Pix

In [45]:
n

9

In [46]:
h = fp+'\\20160208_008_TRACK.dat'

In [47]:
hh,nh = get_header(h)

In [48]:
nh

-1

In [49]:
hh

[]

In [67]:
h

'C:\\Users\\Sunsat\\Documents\\Data\\20160208\\20160208_008_TRACK.dat'

In [251]:
typ,fnum =startype(h)

In [252]:
typ

'track'

In [254]:
int(fnum)

8

In [71]:
typ.lower()

'track'

In [193]:
o = datetime.strptime('20:23:09.015','%H:%M:%S.%f')#,'%H:%M:%S.%s')

In [195]:
utc = o.hour+o.minute/60.0+o.second/3600.0+o.microsecond/3600.0/1000000.0

In [172]:
def mktime(txt):
    return datetime.strptime(txt,'%H:%M:%S.%f')

In [197]:
conv1 = {'Time':mkktime}

In [214]:
def mkktime(txt):
    o = datetime.strptime(txt,'%H:%M:%S.%f')
    return o.hour+o.minute/60.0+o.second/3600.0+o.microsecond/3600.0/1000000.0

In [177]:
conv = {'Time':mktime,1:mktime,'time':mktime}

In [167]:
convv = {1:mktime}

In [190]:
nm = ['N','Time','AzAngle','AzError','ElAngle','ElError','Azpos','Elpos','Vb_t','Vl_r','Vtot','Tsetbox',\
      'Tmonbox','Tbox','Tvnir','Tnir','P1','P2','P3','P4','T1','T2','T3','T4']

In [222]:
new_nm =  ['N','t','Az_deg','Az_corr','El_deg','El_corr','Az_step','El_step',\
           'QdV_TB','QdV_LR','QdV_tot','T_box_set','T_box_mon','T_box','T_spec_uvis',\
           'T_spec_nir','P1','P2','P3','P4','T1','T2','T3','T4']

In [223]:
def convt(t):
    return float(t)*1000.0-273.15

In [224]:
conv = {'t':mkktime,'T_box':lambda t:float(t)*100.0-273.15,\
        'T1':convt,'T2':convt,'T3':convt,'T4':convt}

In [235]:
dd = np.genfromtxt(h,skip_header=2,names=new_nm,delimiter='\t',converters=conv)

In [236]:
dd

array([ (0.0, 22.098945277777776, -209.98, 1.58, 32.256, 1.8288, -10499.0, -4480.0, -1.67251, -1.72876, 1.645996, 0.0, 0.0, 20.424199999999985, 2.918555, 0.089453, 0.235434, 1.585501, -0.045938, -0.045614, 59.16100000000006, 45.88500000000005, 45.754999999999995, 44.16500000000002),
       (1.0, 22.098975555555555, -208.4, 1.2, 33.8544, 1.2024, -10420.0, -4702.0, -1.80332, -2.152881, 2.703809, 0.0, 0.0, 20.521900000000016, 2.920117, 0.089063, 0.232513, 1.579011, -0.054376, -0.053078, 36.212000000000046, 48.384000000000015, 44.327000000000055, 48.547000000000025),
       (2.0, 22.09900583333333, -207.2, 1.42, 35.2872, 1.5336, -10360.0, -4901.0, -3.419141, -3.819189, 4.019434, 0.0, 0.0, 20.404700000000048, 2.895898, 0.089063, 0.235434, 1.564731, -0.050157, -0.054701, 29.94799999999998, 47.346000000000004, 65.16600000000005, 42.80099999999999),
       ...,
       (53082.0, 23.611406111111112, -159.56, 0.0, 31.1976, -0.0, -7978.0, -4333.0, -0.001172, -0.002783, 3.637256, 0.0, 0.0, 20.52190

In [238]:
dd.dtype.names

('N',
 't',
 'Az_deg',
 'Az_corr',
 'El_deg',
 'El_corr',
 'Az_step',
 'El_step',
 'QdV_TB',
 'QdV_LR',
 'QdV_tot',
 'T_box_set',
 'T_box_mon',
 'T_box',
 'T_spec_uvis',
 'T_spec_nir',
 'P1',
 'P2',
 'P3',
 'P4',
 'T1',
 'T2',
 'T3',
 'T4')

In [244]:
def to_dict(d):
    'Simple function to switch from numpy named array to dict with numpy arrays'
    dd = {}
    for n in d.dtype.names:
        dd[n] = d[n]
    return d

In [243]:
ddd['El_temp_K'] = 1000.0*ddd['T1']

In [226]:
import hdf5storage as hs

In [229]:
import scipy.io as sio

In [230]:
m = sio.loadmat('C:\Users\Sunsat\Documents\Data\\20151118star.mat')

In [231]:
m.keys()

['vis_cldp',
 '__version__',
 'track',
 '__header__',
 'vis_sun',
 '__globals__',
 'nir_sun',
 'nir_zen',
 'vis_zen',
 'nir_cldp',
 'program_version']

In [233]:
m['track'].dtype.names

('pname',
 'fname',
 'time',
 'N',
 'T_spec_nir',
 'T_spec_uvis',
 'T_box',
 'T_box_mon',
 'T_box_set',
 'El_deg',
 'El_step',
 'El_corr',
 'Az_deg',
 'Az_step',
 'Az_corr',
 'QdV_tot',
 'QdV_LR',
 'QdV_TB',
 'T1',
 'T2',
 'T3',
 'T4',
 'P1',
 'P2',
 'P3',
 'P4',
 'run_id',
 'El_temp_K',
 'NearWindow_temp_K',
 'Az_temp_K',
 'Can_P_mB',
 'Can_RH',
 't',
 'filename',
 'filen',
 'note')

In [280]:
m['track']['fname']

array([[ array([u'20151118_002_TRACK.dat', u'20151118_003_TRACK.dat',
       u'20151118_004_TRACK.dat', u'20151118_005_TRACK.dat',
       u'20151118_006_TRACK.dat', u'20151118_008_TRACK.dat',
       u'20151118_012_TRACK.dat', u'20151118_021_TRACK.dat',
       u'20151118_022_TRACK.dat', u'20151118_025_TRACK.dat',
       u'20151118_026_TRACK.dat', u'20151118_029_TRACK.dat',
       u'20151118_030_TRACK.dat', u'20151118_031_TRACK.dat',
       u'20151118_032_TRACK.dat', u'20151118_033_TRACK.dat',
       u'20151118_036_TRACK.dat', u'20151118_037_TRACK.dat',
       u'20151118_038_TRACK.dat', u'20151118_043_TRACK.dat',
       u'20151118_044_TRACK.dat', u'20151118_045_TRACK.dat',
       u'20151118_050_TRACK.dat', u'20151118_051_TRACK.dat',
       u'20151118_052_TRACK.dat', u'20151118_053_TRACK.dat',
       u'20151118_058_TRACK.dat', u'20151118_059_TRACK.dat',
       u'20151118_060_TRACK.dat', u'20151118_061_TRACK.dat',
       u'20151118_062_TRACK.dat', u'20151118_063_TRACK.dat',
       u'201511

In [268]:
m['track']['filen'][0][0][:]

array([[ 2],
       [ 2],
       [ 2],
       ..., 
       [77],
       [78],
       [79]], dtype=uint8)

In [264]:
np.arange(len())

array([0])

In [261]:
np.zeros_like(m['track']['filen'])

array([[0]], dtype=object)

In [255]:
m['track']['filen']

array([[ array([[ 2],
       [ 2],
       [ 2],
       ..., 
       [77],
       [78],
       [79]], dtype=uint8)]], dtype=object)

In [273]:
s = {}

In [274]:
s['forj'] = [1,2,3]

In [275]:
s.keys()

['forj']

In [277]:
if 'sun' in s:
    print 'yes'

In [281]:
fparts

NameError: name 'fparts' is not defined

In [283]:
fparts = os.path.split(h)

In [284]:
fparts

('C:\\Users\\Sunsat\\Documents\\Data\\20160208', '20160208_008_TRACK.dat')